import type { DashboardData, OrganizationSummary, RadarEvent } from "@/lib/types";

const now = Date.now();
const minutesAgo = (minutes: number) => new Date(now - minutes * 60_000).toISOString();

export const demoEvents: RadarEvent[] = [
  {
    id: "event-001",
    deviceEventId: "8cc80a23-507d-4fcf-bfe5-97d3a3553ae1",
    deviceId: "rsr-0001",
    deviceName: "RSR-0001",
    organizationName: "RoadSafe Pilot",
    siteName: "Main Road · Northbound",
    capturedAt: minutesAgo(4),
    speedKph: 96,
    speedLimitKph: 60,
    overspeedKph: 36,
    plate: "CA 482 719",
    plateRegion: "ZA",
    plateScore: 0.94,
    plateBox: { xmin: 1284, ymin: 702, xmax: 1554, ymax: 792 },
    photoPath: "demo/event-001.jpg",
    photoUrl: "/api/demo-photo?variant=1",
    photoStatus: "uploaded",
    processingStatus: "complete",
    emailStatus: "delivered",
  },
  {
    id: "event-002",
    deviceEventId: "b4c6b29f-e0e1-4d42-8893-e5277077e516",
    deviceId: "rsr-0001",
    deviceName: "RSR-0001",
    organizationName: "RoadSafe Pilot",
    siteName: "Main Road · Northbound",
    capturedAt: minutesAgo(18),
    speedKph: 83,
    speedLimitKph: 60,
    overspeedKph: 23,
    plate: "ND 71 ZN GP",
    plateRegion: "ZA",
    plateScore: 0.89,
    plateBox: { xmin: 1180, ymin: 680, xmax: 1450, ymax: 770 },
    photoPath: "demo/event-002.jpg",
    photoUrl: "/api/demo-photo?variant=2",
    photoStatus: "uploaded",
    processingStatus: "complete",
    emailStatus: "sent",
  },
  {
    id: "event-003",
    deviceEventId: "22d36e49-b4ef-4bd5-bc6d-a39b1169dc9e",
    deviceId: "rsr-0001",
    deviceName: "RSR-0001",
    organizationName: "RoadSafe Pilot",
    siteName: "Main Road · Northbound",
    capturedAt: minutesAgo(31),
    speedKph: 58,
    speedLimitKph: 60,
    overspeedKph: 0,
    plate: null,
    plateRegion: null,
    plateScore: null,
    plateBox: null,
    photoPath: null,
    photoStatus: "not_required",
    processingStatus: "not_required",
    emailStatus: "not_required",
  },
  {
    id: "event-004",
    deviceEventId: "7d02694d-bb5a-4fad-a0ee-928f2102fe4c",
    deviceId: "rsr-0001",
    deviceName: "RSR-0001",
    organizationName: "RoadSafe Pilot",
    siteName: "Main Road · Northbound",
    capturedAt: minutesAgo(47),
    speedKph: 77,
    speedLimitKph: 60,
    overspeedKph: 17,
    plate: null,
    plateRegion: null,
    plateScore: null,
    plateBox: null,
    photoPath: "demo/event-004.jpg",
    photoUrl: "/api/demo-photo?variant=3",
    photoStatus: "uploaded",
    processingStatus: "pending",
    emailStatus: "pending",
  },
];

export const demoDashboard: DashboardData = {
  organizationName: "RoadSafe Operations",
  role: "roadsafe_admin",
  metrics: {
    totalVehicles: 1248,
    overspeedVehicles: 187,
    overspeedRate: 15.0,
    averageSpeedKph: 54,
    maximumSpeedKph: 127,
    onlineDevices: 1,
    totalDevices: 1,
  },
  devices: [
    {
      id: "rsr-0001",
      serialNumber: "RSR-2026-0001",
      name: "RSR-0001",
      state: "online",
      organizationName: "RoadSafe Pilot",
      siteName: "Main Road · Northbound",
      speedLimitKph: 60,
      lastSeenAt: minutesAgo(0.4),
      softwareVersion: "0.1.0-shadow",
      radarConnected: true,
      cameraConnected: true,
      cpuTemperatureC: 48.7,
      diskUsedPercent: 9,
      queueDepth: 0,
    },
  ],
  recentEvents: demoEvents,
  hourlyTraffic: [
    { hour: "06", vehicles: 72, overspeed: 8 },
    { hour: "07", vehicles: 124, overspeed: 19 },
    { hour: "08", vehicles: 180, overspeed: 34 },
    { hour: "09", vehicles: 156, overspeed: 28 },
    { hour: "10", vehicles: 141, overspeed: 21 },
    { hour: "11", vehicles: 168, overspeed: 25 },
    { hour: "12", vehicles: 192, overspeed: 31 },
    { hour: "13", vehicles: 215, overspeed: 21 },
  ],
};

export const demoOrganizations: OrganizationSummary[] = [
  { id: "org-roadsafe", name: "RoadSafe Internal", status: "active", memberCount: 2, deviceCount: 0 },
  { id: "org-pilot", name: "RoadSafe Pilot", status: "active", memberCount: 3, deviceCount: 1 },
  { id: "org-archived", name: "Northern Logistics", status: "suspended", memberCount: 1, deviceCount: 0 },
];

